---
server:
  port: 7201
spring:
  profiles: consumer1
  application:
    name: small-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
---
server:
  port: 7202
spring:
  profiles: consumer2
  application:
    name: small-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankwechat?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name:  com.mysql.cj.jdbc.Driver



logging:
  level:
    com.zking.mybatisplus : debug


